account/urls.py
from django.urls import path
from .views import sign_up, sign_in, sign_out
from django.conf import settings

urlpatterns = [
    path("register/", sign_up, name="register"),
    path("login/", sign_in, name="login"),
    path(
        "logout/",
        sign_out,
        name="logout",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lms.urls")),
    path("users/", include("account.urls")),
]

lms/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("", views.course_list, name="home"),
    path("courses/<int:id>/", views.course_detail, name="course-detail"),
    path("test/", views.submission)
] 

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

ROLES = [
    ("Teacher", "Teacher"),
    ("Student", "Student"),
]


class User(AbstractUser):
    role = models.CharField(choices=ROLES, max_length=20)

lms/models.py
from django.db import models
from django.db.models import Q
from account.models import User


# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    credit = models.PositiveIntegerField()
    cover_image = models.URLField()
    teacher = models.ForeignKey(
        User, on_delete=models.CASCADE, limit_choices_to=Q(role="Teacher")
    )

    def __str__(self) -> str:
        return self.title


ATTACHMENT_TYPES = [
    ("pdf", "pdf"),
    ("img", "image"),
    ("mp4", "mp4"),
    ("ppt", "ppt"),
]


class Chapter(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    attachment_type = models.CharField(
        max_length=20, choices=ATTACHMENT_TYPES, blank=True, null=True
    )
    attachment = models.FileField(upload_to="attachments", blank=True, null=True)


class Enrollment(models.Model):
    student = models.ForeignKey(
        User, on_delete=models.CASCADE, limit_choices_to=Q(role="Student")
    )
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    approved = models.BooleanField(default=False)

account/forms.py
from django import forms
from account.models import User
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=65)
    password = forms.CharField(max_length=65, widget=forms.PasswordInput)


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "role", "password1", "password2"]
        


class TestForm(forms.Form):
    question = forms.CharField(max_length=100)

account/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse
from .forms import LoginForm, RegisterForm
from django.contrib.auth.models import Group


TEACHER_GROUP_NAME = 'teacher'


def sign_up(request):
    if request.method == "GET":
        form = RegisterForm()
        return render(request, "account/register.html", {"form": form})

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            print(user)
            if form.cleaned_data['role'] == 'Teacher':
                group = Group.objects.get(name=TEACHER_GROUP_NAME)
                user.is_staff = True
                user.groups.add(group)
                user.save()
            # user.save()
            messages.success(request, "You have singed up successfully.")
            login(request, user)
            return redirect(reverse("home"))
        else:
            return render(request, "account/register.html", {"form": form})


def sign_in(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "account/login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect("home")
            else:
                messages.error(request, f"Invalid username or password")
        return render(request, "account/login.html", {"form": form})


def sign_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("login"))

lms/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required

from account.forms import TestForm

from .models import Course, Enrollment


# Create your views here.
# @login_required(login_url="users/login")
def course_list(request):
    return render(request, "lms/courses.html", {"courses": Course.objects.all()})


def course_detail(request, id):
    course = Course.objects.get(pk=id)
    user = request.user
    is_enrolled = Enrollment.objects.filter(student=user, course=course).exists()
    context = {
        'course': course,
        'is_enrolled': is_enrolled
    }
    if request.method == "POST":
        enrollment = Enrollment.objects.create(course=course, student=user)
        return render(request, 'lms/course-detail.html', {'course':course})
    return render(request, "lms/course-detail.html", context)


# class CourseListView(ListView):
#     model = Course
#     queryset = Course.objects.all()
#     paginate_by = 50
#     context_object_name = "courses"
#     template_name = "lms/courses.html"


def submission(request):
    form = TestForm()
    return render(request, 'lms/test.html', {'form': form})

# def enrollment(request):
#     user = request.user()
#     print(user)

lms/templates/lms/course-detail.html
{% extends 'base.html' %} {% block content %}
<div class="row">
  <div class="col-lg-5">
    <div class="card">
      <img class="card-img-top" src="{{course.cover_image}}" alt="" srcset="" />
      <div class="px-4">
        {% if not is_enrolled %}
        <form method="post">
          {% csrf_token %}
          <button class="w-100 my-4 btn btn-outline-primary">Enroll now</button>
        </form>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="col-lg-7">
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">{{course.title}}</h3>
        <p class="card-text text-secondary">{{course.description}}</p>
        <p class="card-text">
          Teacher: <span class="fw-bold">{{course.teacher.username}}</span>
        </p>
      </div>
    </div>
    <div class="card mt-4">
      <div class="card-body">
        <h4>Course Content</h4>
        <ul>
          {% for i in course.chapter_set.all %}
          {% if is_enrolled %}
            <li>{{i.title}}</li>
            <p>{{i.description}}</p>
            <a href="{{i.attachment.url}}">{{i.attachment}}</a>
          {% else %}
            <li>{{i.title}}</li>
          {% endif %}
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

lms/templates/lms/courses.html
{% extends 'base.html' %} {% block content %} {% load static %} {% if messages%}
{% for message in messages %}
<div class="alert alert-success alert-dismissible" role="alert">
  {{message}}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %} {% endif %}
<div class="row g-4">
  {% for course in courses %}
  <div class="col-sm-6 col-lg-4 col-xl-3">
    <div class="card">
      <!-- <img src="{% static 'library/1.jpg' %}" class="card-img-top" alt="..." /> -->
      <img class="card-top-image" src="{{course.cover_image}}" alt="" />
      <div class="card-body">
        <a
          class="link-offset-2 text-dark link-underline link-underline-opacity-0"
          href="/courses/{{course.id}}/"
          ><p class="text-bold m-0">{{course.title}}</p></a
        >
        <p class="text-secondary mt-2">{{course.teacher.username}}</p>
      </div>
    </div>
  </div>
  {%endfor %}
</div>

<script>
  setTimeout(function () {
    bootstrap.Alert.getOrCreateInstance(
      document.querySelector(".alert")
    ).close();
  }, 2000);
</script>

{% endblock %}

lms/templates/lms/test.html
<form action="" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="submit">
</form> 

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </head>
  <body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
      <div class="container">
        <a class="navbar-brand" href="">BDU LMS</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin/">Admin</a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li>
                  <a class="dropdown-item" href="#">Something else here</a>
                </li>
              </ul>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0 me-4">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-bs-toggle="dropdown"
                aria-expanded="false"
              >
                {{user.username}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Edit</a></li>
                <li>
                  <a class="dropdown-item" href="">Enrolled Courses</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                </li>
              </ul>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}" role="button"
                >Login</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}" role="button"
                >Register</a
              >
            </li>
            {% endif %}
          </ul>

          <!-- <form class="d-flex">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-outline-success" type="submit">
              Search
            </button>
          </form> -->
        </div>
      </div>
    </nav>
    <div class="container p-4 rounded-3">{% block content %} {% endblock %}</div>
  </body>
</html>